### ISSUE TITLE
Bug:  !Sub become  !<!Sub> after its parsed

### ISSUE THREAD

**Issue by egut** [gristlabs/yaml-cfn#3]
A simplified version of the program that show the issue
```
#!/usr/bin/env node
const { yamlParse, yamlDump } = require('yaml-cfn');

const input=`AWS: !Sub Foo`;

console.log("input: ", input)
console.log("parsed: ", yamlDump(yamlParse(input)))
```

Output:
```
input:  AWS: !Sub Foo
parsed:  AWS: !<!Sub> Foo
```

Versions:
```
└─┬ yaml-cfn@0.2.0
  └── js-yaml@3.12.0 
```

Node version: v8.12.0

**Comment by dsagal** [comment]
This is expected behavior: see https://yaml.org/spec/1.2/spec.html#id2782457. `!Sub` is a compact shorthand for a primary tag, which is fully written out as `!<!Sub>`. Parsing that produces the same result as the original shorter input.

It's a similar difference to losing comments and quoting: there are many ways to write YAML to produce equivalent structure. Once parsed, only the structure is remembered. Dumping it should produce an equivalent result, but it would usually not be identical.
